<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Activity Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #17479E;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #17479E;
            font-size: 24px;
            margin: 0;
        }
        .header p {
            color: #666;
            margin: 5px 0;
        }
        .summary-stats {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
            text-align: center;
        }
        .stats-grid {
            display: table;
            width: 100%;
        }
        .stats-row {
            display: table-row;
        }
        .stats-cell {
            display: table-cell;
            width: 33.33%;
            text-align: center;
            padding: 10px;
        }
        .stat-number {
            font-size: 24px;
            font-weight: bold;
            color: #17479E;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 10px;
        }
        th {
            background-color: #17479E;
            color: white;
            font-weight: bold;
            padding: 8px;
            text-align: left;
            border: 1px solid #dee2e6;
        }
        td {
            border: 1px solid #dee2e6;
            padding: 6px;
            text-align: left;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .status-active {
            color: #28a745;
            font-weight: bold;
        }
        .status-inactive {
            color: #dc3545;
            font-weight: bold;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #dee2e6;
            padding-top: 10px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>URA SACCOS Users Activity Report</h1>
        <p>Generated on: {{ $generated_at }}</p>
        <p>Generated by: {{ $generated_by }}</p>
    </div>

    <!-- Summary Statistics -->
    <div class="summary-stats">
        <h3 style="color: #17479E; margin-top: 0;">Summary Statistics</h3>
        <div class="stats-grid">
            <div class="stats-row">
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($total_count) }}</div>
                    <div class="stat-label">Total Users</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($users->where('status', 'active')->count()) }}</div>
                    <div class="stat-label">Active Users</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($users->where('last_login', '>=', now()->subDays(7))->count()) }}</div>
                    <div class="stat-label">Active This Week</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Users Table -->
    <h3 style="color: #17479E; border-bottom: 1px solid #17479E; padding-bottom: 5px;">Detailed User Activity</h3>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Branch</th>
                <th>Department</th>
                <th>Role</th>
                <th>Status</th>
                <th>Last Login</th>
                <th>Login Attempts</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $index => $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->phone_number }}</td>
                <td>{{ $user->branch->name ?? 'N/A' }}</td>
                <td>{{ $user->department->name ?? 'N/A' }}</td>
                <td>{{ $user->roles->first()->name ?? 'N/A' }}</td>
                <td class="{{ $user->status === 'active' ? 'status-active' : 'status-inactive' }}">
                    {{ ucfirst($user->status) }}
                </td>
                <td>{{ $user->last_login ? $user->last_login->format('Y-m-d H:i') : 'Never' }}</td>
                <td style="{{ $user->login_attempts >= 3 ? 'color: red; font-weight: bold;' : '' }}">
                    {{ $user->login_attempts }}
                </td>
                <td>{{ $user->created_at->format('Y-m-d') }}</td>
            </tr>

            @if(($index + 1) % 25 == 0 && $index + 1 < $total_count)
            </tbody>
        </table>
        <div class="page-break"></div>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Branch</th>
                    <th>Department</th>
                    <th>Role</th>
                    <th>Status</th>
                    <th>Last Login</th>
                    <th>Login Attempts</th>
                    <th>Created</th>
                </tr>
            </thead>
            <tbody>
            @endif
            @endforeach
        </tbody>
    </table>

    <!-- Analysis Section -->
    <div style="margin-top: 30px; page-break-inside: avoid;">
        <h3 style="color: #17479E; border-bottom: 1px solid #17479E; padding-bottom: 5px;">Activity Analysis</h3>

        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h4 style="color: #17479E; margin-top: 0;">Key Insights:</h4>
            <ul style="line-height: 1.6;">
                <li><strong>User Engagement:</strong> {{ number_format(($users->whereNotNull('last_login')->count() / $total_count) * 100, 1) }}% of users have logged in at least once</li>
                <li><strong>Active Rate:</strong> {{ number_format(($users->where('status', 'active')->count() / $total_count) * 100, 1) }}% of users are currently active</li>
                <li><strong>Recent Activity:</strong> {{ number_format(($users->where('last_login', '>=', now()->subDays(30))->count() / $total_count) * 100, 1) }}% of users logged in within the last 30 days</li>
                @if($users->where('login_attempts', '>=', 3)->count() > 0)
                <li><strong>Security Alert:</strong> {{ $users->where('login_attempts', '>=', 3)->count() }} users have 3+ failed login attempts</li>
                @endif
            </ul>
        </div>

        @php
            $departmentStats = $users->groupBy('department.name')->map(function($deptUsers) {
                return [
                    'total' => $deptUsers->count(),
                    'active' => $deptUsers->where('status', 'active')->count(),
                    'recent' => $deptUsers->where('last_login', '>=', now()->subDays(7))->count()
                ];
            });
        @endphp

        @if($departmentStats->count() > 0)
        <h4 style="color: #17479E;">Department Breakdown:</h4>
        <table style="margin-top: 10px;">
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Total Users</th>
                    <th>Active Users</th>
                    <th>Recent Activity</th>
                    <th>Activity Rate</th>
                </tr>
            </thead>
            <tbody>
                @foreach($departmentStats as $deptName => $stats)
                <tr>
                    <td>{{ $deptName ?: 'Unassigned' }}</td>
                    <td>{{ $stats['total'] }}</td>
                    <td>{{ $stats['active'] }}</td>
                    <td>{{ $stats['recent'] }}</td>
                    <td>{{ $stats['total'] > 0 ? number_format(($stats['recent'] / $stats['total']) * 100, 1) : 0 }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
    </div>

    <div class="footer">
        URA SACCOS Users Activity Report - Confidential Document - {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>