<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Analytics Dashboard Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #17479E;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #17479E;
            font-size: 24px;
            margin: 0;
        }
        .header p {
            color: #666;
            margin: 5px 0;
        }
        .summary-stats {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
            text-align: center;
        }
        .stats-grid {
            display: table;
            width: 100%;
        }
        .stats-row {
            display: table-row;
        }
        .stats-cell {
            display: table-cell;
            width: 25%;
            text-align: center;
            padding: 10px;
        }
        .stat-number {
            font-size: 24px;
            font-weight: bold;
            color: #17479E;
        }
        .stat-label {
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .chart-section {
            margin-bottom: 30px;
        }
        .chart-title {
            color: #17479E;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 15px;
            border-bottom: 1px solid #17479E;
            padding-bottom: 5px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            font-size: 10px;
        }
        th {
            background-color: #17479E;
            color: white;
            font-weight: bold;
            padding: 8px;
            text-align: left;
            border: 1px solid #dee2e6;
        }
        td {
            border: 1px solid #dee2e6;
            padding: 6px;
            text-align: left;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #dee2e6;
            padding-top: 10px;
        }
        .insights-section {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .insights-title {
            color: #17479E;
            font-weight: bold;
            font-size: 16px;
            margin-bottom: 10px;
        }
        .insight-item {
            margin-bottom: 8px;
            line-height: 1.4;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>URA SACCOS Analytics Dashboard Report</h1>
        <p>Generated on: {{ $generated_at }}</p>
        <p>Generated by: {{ $generated_by }}</p>
    </div>

    <!-- Summary Statistics -->
    <div class="summary-stats">
        <h3 style="color: #17479E; margin-top: 0;">Key Performance Metrics</h3>
        <div class="stats-grid">
            <div class="stats-row">
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($total_count) }}</div>
                    <div class="stat-label">Total Users</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($active_count) }}</div>
                    <div class="stat-label">Active Users</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($online_count) }}</div>
                    <div class="stat-label">Currently Online</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($logged_today) }}</div>
                    <div class="stat-label">Logged Today</div>
                </div>
            </div>
        </div>
    </div>

    <!-- Department Analysis -->
    <div class="chart-section">
        <h3 class="chart-title">Department Analysis</h3>
        <table>
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Total Users</th>
                    <th>Percentage</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($departments as $dept)
                <tr>
                    <td>{{ $dept->name }}</td>
                    <td>{{ $dept->users_count ?? 0 }}</td>
                    <td>{{ $total_count > 0 ? number_format((($dept->users_count ?? 0) / $total_count) * 100, 1) : 0 }}%</td>
                    <td>
                        @if(($dept->users_count ?? 0) > 10)
                            High Activity
                        @elseif(($dept->users_count ?? 0) > 5)
                            Medium Activity
                        @else
                            Low Activity
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Branch Analysis -->
    <div class="chart-section">
        <h3 class="chart-title">Branch Distribution</h3>
        <table>
            <thead>
                <tr>
                    <th>Branch</th>
                    <th>Total Users</th>
                    <th>Percentage</th>
                    <th>Performance</th>
                </tr>
            </thead>
            <tbody>
                @foreach($branches as $branch)
                <tr>
                    <td>{{ $branch->name }}</td>
                    <td>{{ $branch->users_count ?? 0 }}</td>
                    <td>{{ $total_count > 0 ? number_format((($branch->users_count ?? 0) / $total_count) * 100, 1) : 0 }}%</td>
                    <td>
                        @if(($branch->users_count ?? 0) > 15)
                            Excellent
                        @elseif(($branch->users_count ?? 0) > 8)
                            Good
                        @else
                            Needs Improvement
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <!-- Key Insights -->
    <div class="insights-section">
        <h4 class="insights-title">Key Insights & Recommendations:</h4>
        <div class="insight-item">
            <strong>User Engagement:</strong> {{ number_format(($active_count / $total_count) * 100, 1) }}% of users are currently active in the system.
        </div>
        <div class="insight-item">
            <strong>Daily Activity:</strong> {{ number_format(($logged_today / $total_count) * 100, 1) }}% of users logged in today, indicating {{ $logged_today > ($total_count * 0.3) ? 'high' : 'moderate' }} system engagement.
        </div>
        <div class="insight-item">
            <strong>Real-time Usage:</strong> {{ $online_count }} users are currently online, representing {{ number_format(($online_count / $total_count) * 100, 1) }}% of the user base.
        </div>
        @if($departments->count() > 0)
        <div class="insight-item">
            <strong>Department Distribution:</strong> Users are distributed across {{ $departments->count() }} departments, with {{ $departments->sortByDesc('users_count')->first()->name ?? 'N/A' }} having the highest user count.
        </div>
        @endif
        @if($branches->count() > 0)
        <div class="insight-item">
            <strong>Branch Performance:</strong> The system covers {{ $branches->count() }} branches, with {{ $branches->sortByDesc('users_count')->first()->name ?? 'N/A' }} being the most active branch.
        </div>
        @endif
    </div>

    <!-- Performance Summary -->
    <div class="chart-section">
        <h3 class="chart-title">Performance Summary</h3>
        <table>
            <thead>
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                    <th>Benchmark</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>User Activation Rate</td>
                    <td>{{ number_format(($active_count / $total_count) * 100, 1) }}%</td>
                    <td>>80%</td>
                    <td style="color: {{ ($active_count / $total_count) * 100 > 80 ? 'green' : 'orange' }};">
                        {{ ($active_count / $total_count) * 100 > 80 ? 'Excellent' : 'Needs Improvement' }}
                    </td>
                </tr>
                <tr>
                    <td>Daily Engagement</td>
                    <td>{{ number_format(($logged_today / $total_count) * 100, 1) }}%</td>
                    <td>>30%</td>
                    <td style="color: {{ ($logged_today / $total_count) * 100 > 30 ? 'green' : 'orange' }};">
                        {{ ($logged_today / $total_count) * 100 > 30 ? 'Good' : 'Below Target' }}
                    </td>
                </tr>
                <tr>
                    <td>Real-time Activity</td>
                    <td>{{ number_format(($online_count / $total_count) * 100, 1) }}%</td>
                    <td>>10%</td>
                    <td style="color: {{ ($online_count / $total_count) * 100 > 10 ? 'green' : 'orange' }};">
                        {{ ($online_count / $total_count) * 100 > 10 ? 'Active' : 'Low Activity' }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="footer">
        URA SACCOS Analytics Dashboard Report - Confidential Document - {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>