<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Branch Manager Report - {{ $branch->name }}</title>
    <style>
        @page {
            margin: 100px 50px;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #17479e;
        }
        .header h1 {
            color: #17479e;
            margin: 0;
            font-size: 24pt;
        }
        .header h2 {
            color: #666;
            margin: 5px 0;
            font-size: 16pt;
            font-weight: normal;
        }
        .info-box {
            background: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-left: 4px solid #17479e;
        }
        .info-box p {
            margin: 5px 0;
        }
        .analytics-section {
            margin-bottom: 30px;
        }
        .analytics-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .analytics-item {
            display: table-cell;
            width: 20%;
            text-align: center;
            padding: 15px;
            background: #f8f9fa;
            border: 2px solid #dee2e6;
        }
        .analytics-item h3 {
            margin: 0;
            color: #17479e;
            font-size: 24pt;
        }
        .analytics-item p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 9pt;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            border: 2px solid #17479e;
        }
        table thead {
            background: #17479e;
            color: white;
        }
        table th, table td {
            padding: 10px;
            text-align: left;
            border: 1px solid #333;
            font-size: 9pt;
            text-transform: uppercase;
        }
        table th {
            font-weight: bold;
            border: 1px solid #fff;
        }
        table tbody tr:nth-child(even) {
            background: #f8f9fa;
        }
        table tbody tr {
            border-bottom: 1px solid #333;
        }
        .status-text {
            font-weight: bold;
            text-transform: uppercase;
        }
        .status-pending {
            color: #856404;
        }
        .status-assigned {
            color: #0c5460;
        }
        .status-approved {
            color: #155724;
        }
        .status-rejected {
            color: #721c24;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #dee2e6;
            font-size: 8pt;
            color: #666;
        }
        .section-title {
            color: #17479e;
            font-size: 14pt;
            margin-top: 25px;
            margin-bottom: 15px;
            padding-bottom: 5px;
            border-bottom: 2px solid #17479e;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Branch Manager Report</h1>
        <h2>USALAMA WA RAIA SACCOS (URA SACCOS)</h2>
        <p style="margin-top: 5px;">URA - CRM SYSTEM</p>
        <p style="font-size: 8pt;">Makao Makuu: Dar es Salaam | Generated on {{ date('d F Y, H:i:s') }}</p>
    </div>

    <!-- Branch Information -->
    <div class="info-box">
        <p><strong>Branch:</strong> {{ $branch->name }}</p>
        <p><strong>District:</strong> {{ $branch->district->name ?? 'N/A' }}</p>
        <p><strong>Region:</strong> {{ $branch->region->name ?? 'N/A' }}</p>
        <p><strong>Report Generated By:</strong> {{ auth()->user()->name }} ({{ auth()->user()->email }})</p>
        <p><strong>Report Date:</strong> {{ date('d F Y, H:i:s') }}</p>
    </div>

    <!-- Analytics Overview -->
    <h3 class="section-title">ENQUIRY STATISTICS</h3>
    <div class="analytics-grid">
        <div class="analytics-item" style="border-right: none;">
            <h3>{{ number_format($analytics['total']) }}</h3>
            <p>Total Enquiries</p>
        </div>
        <div class="analytics-item" style="border-right: none;">
            <h3>{{ number_format($analytics['pending']) }}</h3>
            <p>Pending</p>
        </div>
        <div class="analytics-item" style="border-right: none;">
            <h3>{{ number_format($analytics['assigned']) }}</h3>
            <p>Assigned</p>
        </div>
        <div class="analytics-item" style="border-right: none;">
            <h3>{{ number_format($analytics['approved']) }}</h3>
            <p>Approved</p>
        </div>
    </div>

    <!-- Enquiries Table -->
    <h3 class="section-title">ENQUIRY DETAILS</h3>
    <table>
        <thead>
            <tr>
                <th style="width: 4%;">#</th>
                <th style="width: 9%;">Date</th>
                <th style="width: 11%;">Check No</th>
                <th style="width: 16%;">Member</th>
                <th style="width: 14%;">Type</th>
                <th style="width: 13%;">Region</th>
                <th style="width: 13%;">District</th>
                <th style="width: 12%;">Registered By</th>
                <th style="width: 8%;">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($enquiries as $index => $enquiry)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $enquiry->created_at->format('d/m/Y') }}</td>
                <td>{{ strtoupper($enquiry->check_number) }}</td>
                <td>{{ strtoupper($enquiry->full_name ?? 'N/A') }}</td>
                <td>{{ strtoupper(str_replace('_', ' ', $enquiry->type)) }}</td>
                <td>{{ strtoupper($enquiry->region->name ?? 'N/A') }}</td>
                <td>{{ strtoupper($enquiry->district->name ?? 'N/A') }}</td>
                <td>{{ $enquiry->registeredBy ? strtoupper($enquiry->registeredBy->name) : 'N/A' }}</td>
                <td>{{ strtoupper($enquiry->status) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" style="text-align: center; padding: 30px; color: #999;">
                    No enquiries found
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>


    <!-- Footer -->
    <div class="footer">
        <p><strong>USALAMA WA RAIA SACCOS (URA SACCOS) - CRM SYSTEM</strong></p>
        <p>This is a computer-generated report. Generated on {{ date('d F Y, H:i:s') }}</p>
        <p>&copy; {{ date('Y') }} URA SACCOS. All rights reserved. | Makao Makuu: Dar es Salaam</p>
    </div>
</body>
</html>