<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 11px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            background: linear-gradient(135deg, #17479E 0%, #0F3678 100%);
            color: white;
            padding: 20px;
            border-radius: 10px;
        }

        .header h1 {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }

        .header h2 {
            margin: 5px 0 0 0;
            font-size: 14px;
            font-weight: normal;
            opacity: 0.9;
        }

        .report-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }

        .report-info div {
            flex: 1;
        }

        .report-info strong {
            color: #17479E;
        }

        .summary-stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 20px;
            padding: 15px;
            background-color: #e9ecef;
            border-radius: 5px;
        }

        .stat-item {
            text-align: center;
        }

        .stat-number {
            font-size: 16px;
            font-weight: bold;
            color: #17479E;
        }

        .stat-label {
            font-size: 10px;
            color: #666;
            margin-top: 2px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            background: white;
        }

        th {
            background-color: #17479E;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-weight: bold;
            font-size: 10px;
        }

        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
            font-size: 9px;
            vertical-align: top;
        }

        tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        .role-badge {
            background-color: #ffc107;
            color: #000;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }

        .route-cell {
            color: #dc3545;
            font-weight: bold;
            word-break: break-all;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>UGANDA REVENUE AUTHORITY</h1>
        <h2>{{ $title }}</h2>
    </div>

    <div class="report-info">
        <div><strong>Total Records:</strong> {{ $total_count }}</div>
        <div><strong>Generated:</strong> {{ $generated_at }}</div>
        <div><strong>Generated By:</strong> {{ $generated_by }}</div>
    </div>

    <div class="summary-stats">
        <div class="stat-item">
            <div class="stat-number">{{ $total_count }}</div>
            <div class="stat-label">Total Attempts</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $attempts->pluck('user_name')->unique()->count() }}</div>
            <div class="stat-label">Unique Users</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ $attempts->where('date', now()->format('d/m/Y'))->count() }}</div>
            <div class="stat-label">Today's Attempts</div>
        </div>
    </div>

    @if($attempts->count() > 0)
        <table>
            <thead>
                <tr>
                    <th style="width: 12%">User Name</th>
                    <th style="width: 10%">Phone</th>
                    <th style="width: 8%">Role</th>
                    <th style="width: 12%">Region</th>
                    <th style="width: 10%">Branch</th>
                    <th style="width: 10%">District</th>
                    <th style="width: 18%">Page Attempted</th>
                    <th style="width: 8%">Date</th>
                    <th style="width: 6%">Time</th>
                    <th style="width: 6%">Year</th>
                </tr>
            </thead>
            <tbody>
                @foreach($attempts as $index => $attempt)
                    @if($index > 0 && $index % 25 == 0)
                        </tbody>
                        </table>
                        <div class="page-break"></div>
                        <table>
                            <thead>
                                <tr>
                                    <th style="width: 12%">User Name</th>
                                    <th style="width: 10%">Phone</th>
                                    <th style="width: 8%">Role</th>
                                    <th style="width: 12%">Region</th>
                                    <th style="width: 10%">Branch</th>
                                    <th style="width: 10%">District</th>
                                    <th style="width: 18%">Page Attempted</th>
                                    <th style="width: 8%">Date</th>
                                    <th style="width: 6%">Time</th>
                                    <th style="width: 6%">Year</th>
                                </tr>
                            </thead>
                            <tbody>
                    @endif
                    <tr>
                        <td><strong>{{ $attempt['user_name'] }}</strong></td>
                        <td>{{ $attempt['user_phone'] }}</td>
                        <td><span class="role-badge">{{ $attempt['user_role'] }}</span></td>
                        <td>{{ $attempt['region'] }}</td>
                        <td>{{ $attempt['branch'] }}</td>
                        <td>{{ $attempt['district'] }}</td>
                        <td class="route-cell">{{ $attempt['route_attempted'] }}</td>
                        <td>{{ $attempt['date'] }}</td>
                        <td>{{ $attempt['time'] }}</td>
                        <td>{{ $attempt['year'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div style="text-align: center; padding: 40px; background-color: #d4edda; color: #155724; border-radius: 5px;">
            <h3>No Unauthorized Access Attempts Found</h3>
            <p>System security is functioning properly!</p>
        </div>
    @endif

    <div class="footer">
        <p>This report contains sensitive security information. Handle with care and distribute only to authorized personnel.</p>
        <p>Generated by URA ERP Security System on {{ $generated_at }}</p>
    </div>
</body>
</html>