<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Frequent Unauthorized Access Attempts Report</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 10px;
            color: #333;
            margin: 0;
            padding: 15px;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #DC3545;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #DC3545;
            font-size: 24px;
            margin: 0;
            font-weight: bold;
        }
        .header .subtitle {
            color: #17479E;
            font-size: 16px;
            margin: 10px 0;
            font-weight: 600;
        }
        .header p {
            color: #666;
            margin: 5px 0;
            font-size: 11px;
        }
        .summary-stats {
            background: #fff3cd;
            border: 2px solid #ffc107;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 30px;
            text-align: center;
        }
        .stats-grid {
            display: table;
            width: 100%;
        }
        .stats-row {
            display: table-row;
        }
        .stats-cell {
            display: table-cell;
            width: 33.33%;
            text-align: center;
            padding: 10px;
        }
        .stat-number {
            font-size: 20px;
            font-weight: bold;
            color: #DC3545;
        }
        .stat-label {
            font-size: 10px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .alert-box {
            background: #f8d7da;
            border: 2px solid #DC3545;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 25px;
            color: #721c24;
            text-align: center;
        }
        .alert-box h3 {
            margin: 0 0 10px 0;
            color: #DC3545;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 8px;
        }
        th {
            background-color: #DC3545;
            color: white;
            font-weight: bold;
            padding: 5px 3px;
            text-align: left;
            border: 1px solid #dee2e6;
            font-size: 8px;
        }
        td {
            border: 1px solid #dee2e6;
            padding: 3px 2px;
            text-align: left;
            font-size: 7px;
            line-height: 1.2;
        }
        tr:nth-child(even) {
            background-color: #f8f9fa;
        }
        .high-risk {
            background-color: #f8d7da !important;
            color: #721c24;
            font-weight: bold;
        }
        .attempt-count {
            background: #DC3545;
            color: white;
            padding: 2px 6px;
            border-radius: 10px;
            font-weight: bold;
            text-align: center;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 9px;
            color: #666;
            border-top: 1px solid #dee2e6;
            padding-top: 10px;
        }
        .security-notice {
            background: #d1ecf1;
            border: 1px solid #bee5eb;
            border-radius: 6px;
            padding: 12px;
            margin-top: 20px;
            color: #0c5460;
            font-size: 9px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚨 SECURITY ALERT REPORT</h1>
        <div class="subtitle">Frequent Unauthorized Access Attempts</div>
        <p>Generated on: {{ $generated_at }}</p>
        <p>Generated by: {{ $generated_by }}</p>
        <p>Period: {{ $period }}</p>
    </div>

    <!-- Alert Box -->
    <div class="alert-box">
        <h3>⚠️ CRITICAL SECURITY NOTICE</h3>
        <p>The following users have attempted to access restricted pages 3 or more times within {{ $period }}. This may indicate potential security breaches or role configuration issues.</p>
    </div>

    <!-- Summary Statistics -->
    <div class="summary-stats">
        <h3 style="color: #DC3545; margin-top: 0;">Summary Statistics</h3>
        <div class="stats-grid">
            <div class="stats-row">
                <div class="stats-cell">
                    <div class="stat-number">{{ number_format($total_users) }}</div>
                    <div class="stat-label">Users with Frequent Attempts</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">{{ $period }}</div>
                    <div class="stat-label">Monitoring Period</div>
                </div>
                <div class="stats-cell">
                    <div class="stat-number">3+</div>
                    <div class="stat-label">Minimum Attempts Threshold</div>
                </div>
            </div>
        </div>
    </div>

    @if($frequent_attempts->count() > 0)
    <!-- Frequent Attempts Table -->
    <h3 style="color: #DC3545; border-bottom: 2px solid #DC3545; padding-bottom: 5px;">🔍 Detailed Frequent Attempts Report</h3>

    <table>
        <thead>
            <tr>
                <th style="width: 15%;">User Name</th>
                <th style="width: 12%;">Phone Number</th>
                <th style="width: 10%;">Role</th>
                <th style="width: 12%;">Region</th>
                <th style="width: 12%;">Branch</th>
                <th style="width: 12%;">District</th>
                <th style="width: 8%;">Attempts</th>
                <th style="width: 12%;">Last Attempt</th>
                <th style="width: 20%;">Routes Attempted</th>
            </tr>
        </thead>
        <tbody>
            @foreach($frequent_attempts as $index => $attempt)
            <tr class="{{ $attempt['attempt_count'] >= 5 ? 'high-risk' : '' }}">
                <td style="word-wrap: break-word; font-weight: 600;">{{ $attempt['user_name'] }}</td>
                <td>{{ $attempt['user_phone'] }}</td>
                <td style="font-weight: 500;">{{ $attempt['user_role'] }}</td>
                <td>{{ $attempt['region'] }}</td>
                <td>{{ $attempt['branch'] }}</td>
                <td>{{ $attempt['district'] }}</td>
                <td style="text-align: center;">
                    <span class="attempt-count">{{ $attempt['attempt_count'] }}</span>
                </td>
                <td style="font-size: 6px;">{{ $attempt['last_attempt'] }}</td>
                <td style="font-size: 6px; word-wrap: break-word;">{{ \Str::limit($attempt['routes_attempted'], 50) }}</td>
            </tr>

            @if(($index + 1) % 15 == 0 && $index + 1 < $frequent_attempts->count())
            </tbody>
        </table>
        <div class="page-break"></div>
        <table>
            <thead>
                <tr>
                    <th style="width: 15%;">User Name</th>
                    <th style="width: 12%;">Phone Number</th>
                    <th style="width: 10%;">Role</th>
                    <th style="width: 12%;">Region</th>
                    <th style="width: 12%;">Branch</th>
                    <th style="width: 12%;">District</th>
                    <th style="width: 8%;">Attempts</th>
                    <th style="width: 12%;">Last Attempt</th>
                    <th style="width: 20%;">Routes Attempted</th>
                </tr>
            </thead>
            <tbody>
            @endif
            @endforeach
        </tbody>
    </table>

    <!-- Risk Analysis Section -->
    <div style="margin-top: 30px; page-break-inside: avoid;">
        <h3 style="color: #DC3545; border-bottom: 2px solid #DC3545; padding-bottom: 5px;">📊 Risk Analysis</h3>

        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
            <h4 style="color: #DC3545; margin-top: 0;">Security Insights:</h4>
            <ul style="line-height: 1.6; font-size: 9px;">
                <li><strong>High Risk Users:</strong> {{ $frequent_attempts->where('attempt_count', '>=', 5)->count() }} users have 5+ unauthorized attempts</li>
                <li><strong>Most Frequent Attacker:</strong> {{ $frequent_attempts->sortByDesc('attempt_count')->first()['user_name'] ?? 'N/A' }} with {{ $frequent_attempts->sortByDesc('attempt_count')->first()['attempt_count'] ?? 0 }} attempts</li>
                <li><strong>Average Attempts:</strong> {{ number_format($frequent_attempts->avg('attempt_count'), 1) }} attempts per user</li>
                @php
                    $roleBreakdown = $frequent_attempts->groupBy('user_role')->map(function($group) {
                        return $group->count();
                    })->sortDesc();
                @endphp
                <li><strong>Most Problematic Role:</strong> {{ $roleBreakdown->keys()->first() ?? 'N/A' }} ({{ $roleBreakdown->first() ?? 0 }} users)</li>
            </ul>
        </div>

        @if($roleBreakdown->count() > 0)
        <h4 style="color: #DC3545;">Role Breakdown:</h4>
        <table style="margin-top: 10px; width: 60%;">
            <thead>
                <tr>
                    <th>User Role</th>
                    <th>Number of Users</th>
                    <th>Total Attempts</th>
                    <th>Risk Level</th>
                </tr>
            </thead>
            <tbody>
                @foreach($roleBreakdown as $role => $userCount)
                @php
                    $totalAttemptsForRole = $frequent_attempts->where('user_role', $role)->sum('attempt_count');
                    $riskLevel = $totalAttemptsForRole >= 15 ? 'HIGH' : ($totalAttemptsForRole >= 8 ? 'MEDIUM' : 'LOW');
                    $riskColor = $totalAttemptsForRole >= 15 ? '#DC3545' : ($totalAttemptsForRole >= 8 ? '#FFC107' : '#28A745');
                @endphp
                <tr>
                    <td>{{ $role ?: 'Unassigned' }}</td>
                    <td style="text-align: center;">{{ $userCount }}</td>
                    <td style="text-align: center;">{{ $totalAttemptsForRole }}</td>
                    <td style="text-align: center; color: {{ $riskColor }}; font-weight: bold;">{{ $riskLevel }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
    </div>

    <div class="security-notice">
        <strong>🔒 RECOMMENDED ACTIONS:</strong><br>
        1. Review role assignments for users with frequent unauthorized attempts<br>
        2. Contact users directly to verify their access requirements<br>
        3. Consider temporary access restrictions for high-risk users<br>
        4. Monitor these users closely for continued unauthorized access patterns<br>
        5. Update role permissions if business requirements have changed
    </div>

    @else
    <!-- No Frequent Attempts -->
    <div style="text-align: center; padding: 40px; background: #d4edda; border: 2px solid #28a745; border-radius: 10px;">
        <h3 style="color: #155724; margin-top: 0;">✅ EXCELLENT SECURITY STATUS</h3>
        <p style="color: #155724; font-size: 12px;">No users have made frequent unauthorized access attempts in {{ $period }}.</p>
        <p style="color: #155724; font-size: 10px;">Your system security is functioning properly!</p>
    </div>
    @endif

    <div class="footer">
        🔐 URA SACCOS Security Report - CONFIDENTIAL DOCUMENT - {{ now()->format('d F Y, H:i:s') }}
        <br>This report contains sensitive security information and should be handled according to your organization's security policies.
    </div>
</body>
</html>